[build]
  base = "apps/ttp-appointments/"
  publish = "dist/"
  command = "yarn build"

[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = '3.5.1'

[[redirects]]
from = "/*"
to = "/"
status = 200
